### ISSUE TITLE
add with overflow stream.rs:456:13

### ISSUE THREAD

**Issue by xnorpx** [webrtc-rs/sctp-proto#5]
Hitting a panic here: 

thread 'tokio-runtime-worker' panicked at 'attempt to add with overflow', /secret_path_here/d5cf6c4d7dd7baa0/sctp-proto-0.1.4/src/association/stream.rs:456:13

       // RFC 4960 Sec 6.6
        // Note: When transmitting ordered and unordered data, an endpoint does
        // not increment its Stream Sequence Number when transmitting a DATA
        // chunk with U flag set to 1.
        if !unordered {
            self.sequence_number += 1;
        }

This should probably be a wrapping add?

**Comment by rainliu** [comment]
fix in v0.1.5

**Comment by xnorpx** [comment]
Thanks!
